
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#ifndef G_INC_UIB_H_
#define G_INC_UIB_H_

#define DEF_USE_UIB_PROGRAM_MODEL_VER		(3)
#define DEF_UIB_VIEW_MAX_NUM            (100)
#define USE_USER_VIEW					  "USE_USER_VIEW"



#include <Elementary.h>
#include <efl_extension.h>
#include <app.h>

#include <elm_app.h>
#include <system_info.h>
#include <dlog.h>
#include <appfw/app_resource_manager.h>
#include "app_main.h"
#include "uib_util.h"

#endif /* G_INC_UIB_H_ */

