
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

#ifndef UIB_VIEWS_INC_H_
#define UIB_VIEWS_INC_H_

#include "uib_view_main_view.h"

#endif /* UIB_VIEWS_INC_H_ */
