/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "view_data.h"
#include "uib_app_manager.h"
#include "uib_views.h"
#include "uib_views_inc.h"

typedef struct _uib_view_main_control_context {
	/* add your variables here */

} uib_view_main_control_context;

/**
 * @brief The user clicked the hoversel button and popped up the sel.
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void view_main_hoversel_mode_onclicked(uib_view_main_view_context *vc, Evas_Object *obj, void *event_info) {
	elm_hoversel_auto_update_set(obj, EINA_TRUE);
}

/**
 * @brief The entry has been clicked (mouse press and release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void view_main_entry_server_ip_onclicked(uib_view_main_view_context *vc, Evas_Object *obj, void *event_info) {
	elm_entry_input_panel_layout_set(obj,ELM_INPUT_PANEL_LAYOUT_NUMBERONLY);
}

/**
 * @brief The entry has been clicked (mouse press and release).
 *
 * @param vc It is context of the view that this event occurred on. It has all of UI components that this view consist of.
 * @param obj It is UI component itself that emits the event signal.
 * @param event_info
 * 		event_info is NULL
 *
 */
void view_main_entry_server_port_onclicked(uib_view_main_view_context *vc, Evas_Object *obj, void *event_info) {
	elm_entry_input_panel_layout_set(obj,ELM_INPUT_PANEL_LAYOUT_NUMBERONLY);
}

